#!/bin/bash
#
# Generate crontab entries for database backups
# Run this script to install/update the backup cron schedule
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKUP_SCRIPT="${SCRIPT_DIR}/run_backup.sh"
VERIFY_SCRIPT="${SCRIPT_DIR}/verify_backups.sh"

# Create crontab entries
CRON_ENTRIES="# Database Backup Cron Schedule
# Generated by backup_setup.sh

# Full backup - Daily at 2:00 AM
0 2 * * * ${BACKUP_SCRIPT} full >> ${SCRIPT_DIR}/logs/cron_backup.log 2>&1

# Incremental backup - Every 6 hours
0 */6 * * * ${BACKUP_SCRIPT} incremental >> ${SCRIPT_DIR}/logs/cron_backup.log 2>&1

# Backup verification - Daily at 6:00 AM
0 6 * * * ${VERIFY_SCRIPT} >> ${SCRIPT_DIR}/logs/cron_verify.log 2>&1

# Monthly full backup retention cleanup - 1st day of month at 3:00 AM
0 3 1 * * find ${SCRIPT_DIR}/../* -name \"*.log\" -mtime +90 -delete
"

# Output crontab entries
echo "$CRON_ENTRIES"

# Optionally install (uncomment to enable)
# echo "$CRON_ENTRIES" | crontab -

echo ""
echo "To install these crontab entries, run:"
echo "  ./backup_setup.sh | crontab -"
echo ""
echo "Or add manually to your crontab:"
echo "  crontab -e"
