#!/bin/bash
#
# Generate crontab entries for database backups
# Run this script to install/update the backup cron schedule
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKUP_SCRIPT="${SCRIPT_DIR}/run_backup.sh"
VERIFY_SCRIPT="${SCRIPT_DIR}/verify_backups.sh"
NOTIFICATION_SCRIPT="${SCRIPT_DIR}/notify.sh"

# Load configuration
if [ -f "${SCRIPT_DIR}/config/backup.conf" ]; then
    source "${SCRIPT_DIR}/config/backup.conf"
fi

# Set defaults if not loaded from config
BACKUP_HOUR="${BACKUP_HOUR:-2}"
BACKUP_MINUTE="${BACKUP_MINUTE:-0}"
BACKUP_RETENTION_DAYS="${BACKUP_RETENTION_DAYS:-7}"
HEALTHCHECK_URL="${HEALTHCHECK_URL:-}"

# Create logs directory if it doesn't exist
mkdir -p "${SCRIPT_DIR}/logs"
chmod 700 "${SCRIPT_DIR}/logs"

# Create crontab entries
CRON_ENTRIES="# =============================================
# Database Backup Cron Schedule
# Generated by backup_setup.sh
# =============================================

# Full backup - Daily at ${BACKUP_HOUR}:${BACKUP_MINUTE} AM
${BACKUP_MINUTE} ${BACKUP_HOUR} * * * ${BACKUP_SCRIPT} full >> ${SCRIPT_DIR}/logs/cron_backup.log 2>&1

# Backup verification - Daily at 6:00 AM (after backup)
0 6 * * * ${VERIFY_SCRIPT} >> ${SCRIPT_DIR}/logs/cron_verify.log 2>&1

# Cleanup old logs - Weekly on Sunday at 4:00 AM
0 4 * * 0 find ${SCRIPT_DIR}/logs -name \"*.log\" -mtime +${BACKUP_RETENTION_DAYS} -delete 2>/dev/null

# Healthcheck ping - Every hour
0 * * * * curl -s -m 10 ${HEALTHCHECK_URL} > /dev/null 2>&1 || true

# ============================================="

# Output crontab entries
echo "$CRON_ENTRIES"

# Check if running in install mode
if [[ "${1:-}" == "--install" ]]; then
    echo ""
    echo "Installing backup cron schedule..."

    # Backup existing crontab
    crontab -l 2>/dev/null > "${SCRIPT_DIR}/logs/crontab_backup_$(date +%Y%m%d_%H%M%S).txt" || true

    # Install new crontab (suppress MAILTO warnings)
    CRON_WITH_MAILTO="MAILTO=\"\"\n${CRON_ENTRIES}"
    echo -e "$CRON_WITH_MAILTO" | crontab - 2>/dev/null || {
        # Fallback: save to file and instruct user
        echo "$CRON_ENTRIES" > "${SCRIPT_DIR}/crontab.txt"
        echo "⚠️  Could not install crontab directly."
        echo "   Cron schedule saved to: ${SCRIPT_DIR}/crontab.txt"
        echo "   Install manually with: crontab ${SCRIPT_DIR}/crontab.txt"
    }

    # Verify installation
    CRON_INSTALLED=$(crontab -l 2>/dev/null | grep -c "run_backup.sh" || echo "0")
    if [ "$CRON_INSTALLED" -gt 0 ]; then
        echo "✅ Cron schedule installed successfully!"
        echo ""
        echo "Current crontab:"
        crontab -l
    fi
else
    echo ""
    echo "To install these crontab entries, run:"
    echo "  ./backup_setup.sh --install"
    echo ""
    echo "Or add manually to your crontab:"
    echo "  crontab -e"
fi

echo ""
echo "============================================="
echo "Backup System Status:"
echo "============================================="
echo "  Backup directory: ${BACKUP_DIR}"
echo "  Retention: ${BACKUP_RETENTION_DAYS} days"
echo "  Encryption: ${ENCRYPT_BACKUPS}"
echo "  S3 Upload: ${S3_ENABLED}"
echo "  Notifications: $([ -n "$SLACK_WEBHOOK_URL" ] && echo 'Slack configured' || echo 'Not configured')"
echo "============================================="
