
// Mock enums for Prisma SQLite compatibility

export enum SubscriptionStatus {
  INACTIVE = 'INACTIVE',
  TRIALING = 'TRIALING',
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  CANCELED = 'CANCELED',
  PAUSED = 'PAUSED',
  UNPAID = 'UNPAID'
}

export enum BillingType {
  SUBSCRIPTION = 'SUBSCRIPTION',
  UPGRADE = 'UPGRADE',
  DOWNGRADE = 'DOWNGRADE',
  RENEWAL = 'RENEWAL',
  REFUND = 'REFUND',
  CREDIT = 'CREDIT',
  TRIAL_CONVERSION = 'TRIAL_CONVERSION',
  ONE_TIME = 'ONE_TIME'
}

export enum BillingStatus {
  PENDING = 'PENDING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  CANCELED = 'CANCELED',
  REFUNDED = 'REFUNDED'
}

export enum TrialStatus {
  ACTIVE = 'ACTIVE',
  CONVERTED = 'CONVERTED',
  EXPIRED = 'EXPIRED',
  CANCELED = 'CANCELED'
}

export enum ChangeType {
  UPGRADE = 'UPGRADE',
  DOWNGRADE = 'DOWNGRADE',
  CROSSGRADE = 'CROSSGRADE',
  CANCELLATION = 'CANCELLATION',
  REACTIVATION = 'REACTIVATION'
}

export enum ReminderStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  CANCELED = 'CANCELED'
}

export enum ReminderType {
  TRIAL_EXPIRING = 'TRIAL_EXPIRING',
  TRIAL_EXPIRED = 'TRIAL_EXPIRED',
  SUBSCRIPTION_EXPIRING = 'SUBSCRIPTION_EXPIRING',
  SUBSCRIPTION_RENEWED = 'SUBSCRIPTION_RENEWED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_SUCCEEDED = 'PAYMENT_SUCCEEDED',
  UPGRADE_SUGGESTION = 'UPGRADE_SUGGESTION',
  WINBACK = 'WINBACK'
}

export enum BillingCycle {
  MONTHLY = 'MONTHLY',
  YEARLY = 'YEARLY'
}

export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  OPEN = 'OPEN',
  PAID = 'PAID',
  VOID = 'VOID',
  UNCOLLECTIBLE = 'UNCOLLECTIBLE',
  FORGIVEN = 'FORGIVEN'
}

export enum DiscountType {
  PERCENT = 'PERCENT',
  FIXED = 'FIXED'
}

export enum CouponDuration {
  ONCE = 'ONCE',
  REPEATING = 'REPEATING',
  FOREVER = 'FOREVER'
}

export enum PointTransactionType {
  PURCHASE = 'PURCHASE',
  PURCHASE_BONUS = 'PURCHASE_BONUS',
  DAILY_LOGIN = 'DAILY_LOGIN',
  REFERRAL_SIGNUP = 'REFERRAL_SIGNUP',
  REFERRAL_PURCHASE = 'REFERRAL_PURCHASE',
  BIRTHDAY_BONUS = 'BIRTHDAY_BONUS',
  TIER_BONUS = 'TIER_BONUS',
  FIRST_PURCHASE = 'FIRST_PURCHASE',
  REVIEW = 'REVIEW',
  SOCIAL_SHARE = 'SOCIAL_SHARE',
  PROFILE_COMPLETE = 'PROFILE_COMPLETE',
  EVENT_BONUS = 'EVENT_BONUS',
  EXPIRATION = 'EXPIRATION',
  MANUAL_ADJUSTMENT = 'MANUAL_ADJUSTMENT',
  GAMIFICATION = 'GAMIFICATION'
}

export enum RedemptionStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED'
}

export enum LoyaltyTierLevel {
  BRONZE = 'BRONZE',
  SILVER = 'SILVER',
  GOLD = 'GOLD',
  PLATINUM = 'PLATINUM',
  DIAMOND = 'DIAMOND'
}
