export enum SubscriptionStatus {
  INACTIVE = 'INACTIVE',
  TRIALING = 'TRIALING',
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  CANCELED = 'CANCELED',
  PAUSED = 'PAUSED',
  UNPAID = 'UNPAID',
}

export enum BillingCycle {
  MONTHLY = 'MONTHLY',
  YEARLY = 'YEARLY',
}

export enum BillingType {
  SUBSCRIPTION = 'SUBSCRIPTION',
  UPGRADE = 'UPGRADE',
  DOWNGRADE = 'DOWNGRADE',
  RENEWAL = 'RENEWAL',
  REFUND = 'REFUND',
  CREDIT = 'CREDIT',
  TRIAL_CONVERSION = 'TRIAL_CONVERSION',
  ONE_TIME = 'ONE_TIME',
}

export enum BillingStatus {
  PENDING = 'PENDING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  CANCELED = 'CANCELED',
  REFUNDED = 'REFUNDED',
}

export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  OPEN = 'OPEN',
  PAID = 'PAID',
  VOID = 'VOID',
  UNCOLLECTIBLE = 'UNCOLLECTIBLE',
  FORGIVEN = 'FORGIVEN',
}

export enum ChangeType {
  UPGRADE = 'UPGRADE',
  DOWNGRADE = 'DOWNGRADE',
  CROSSGRADE = 'CROSSGRADE',
  CANCELLATION = 'CANCELLATION',
  REACTIVATION = 'REACTIVATION',
}

export enum ReminderType {
  TRIAL_EXPIRING = 'TRIAL_EXPIRING',
  TRIAL_EXPIRED = 'TRIAL_EXPIRED',
  SUBSCRIPTION_EXPIRING = 'SUBSCRIPTION_EXPIRING',
  SUBSCRIPTION_RENEWED = 'SUBSCRIPTION_RENEWED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_SUCCEEDED = 'PAYMENT_SUCCEEDED',
  UPGRADE_SUGGESTION = 'UPGRADE_SUGGESTION',
  WINBACK = 'WINBACK',
}

export enum ReminderStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  CANCELED = 'CANCELED',
}

export enum TrialStatus {
  ACTIVE = 'ACTIVE',
  CONVERTED = 'CONVERTED',
  EXPIRED = 'EXPIRED',
  CANCELED = 'CANCELED',
}

export enum DiscountType {
  PERCENT = 'PERCENT',
  FIXED = 'FIXED',
}

export enum CouponDuration {
  ONCE = 'ONCE',
  REPEATING = 'REPEATING',
  FOREVER = 'FOREVER',
}
